using FluentAssertions;
using Microsoft.Graph.Models;
using VisuAuth.Abstractions.Users;
using VisuAuth.EntraExternal.Mapping;
using Xunit;
using GraphUser = Microsoft.Graph.Models.User;

namespace VisuAuth.UnitTests.EntraExternal;

/// <summary>
/// Lock-down for the External adapter's projection layer. The shape that
/// matters most here is the <c>identities[]</c> entry on Create — it's
/// the differentiator from Workforce. Read-side projections also have to
/// prefer the customer-typed email (identities) over the auto-generated
/// UPN (<c>cpim_{guid}@…</c>) so the admin grid reads cleanly.
/// </summary>
public sealed class EntraExternalUserMapperTests
{
    // Hoisted to satisfy CA1861 ("avoid allocating a fresh array each call")
    // — the fact data is the same shape across the roles-related test.
    private static readonly string[] TwoRoleArray = ["Admin", "Editor"];

    [Fact]
    public void ToSummary_PrefersIdentitiesEmail_OverAutoGeneratedUpn()
    {
        // The External UPN is ugly: cpim_{guid}@{tenant}.onmicrosoft.com.
        // The customer-friendly value is the identities[].issuerAssignedId.
        // The admin grid must show the latter so operators recognise it.
        var user = new GraphUser
        {
            Id = "u-1",
            UserPrincipalName = "cpim_abcdef@contoso.onmicrosoft.com",
            Mail = null,
            Identities =
            [
                new ObjectIdentity
                {
                    SignInType = "emailAddress",
                    Issuer = "contoso.onmicrosoft.com",
                    IssuerAssignedId = "alice@personal.example",
                },
            ],
            AccountEnabled = true,
        };

        var summary = EntraExternalUserMapper.ToSummary(user);

        summary.Email.Should().Be("alice@personal.example",
            "the customer typed this on signup — surfacing the cpim_ UPN would confuse the admin");
        summary.UserName.Should().Be("alice@personal.example",
            "user name in External is the same as the customer-friendly email by convention");
    }

    [Fact]
    public void ToSummary_FallsBackToMail_ThenUpn_WhenNoIdentitiesEntry()
    {
        var user = new GraphUser
        {
            Id = "u-2",
            UserPrincipalName = "bob@contoso.onmicrosoft.com",
            Mail = "bob@published.example",
            Identities = null,
        };

        var summary = EntraExternalUserMapper.ToSummary(user);

        summary.Email.Should().Be("bob@published.example",
            "no identities[] entry → fall through to mail before UPN");
    }

    [Fact]
    public void ToSummary_AccountEnabledNull_DefaultsToTrue()
    {
        var user = new GraphUser { Id = "u-3", AccountEnabled = null };

        EntraExternalUserMapper.ToSummary(user).IsEnabled.Should().BeTrue(
            "a freshly-fetched user with null accountEnabled is typically a new row — default enabled rather than misreport as locked");
    }

    [Fact]
    public void ToSummary_NonEmailSignInType_IsIgnoredForEmailResolution()
    {
        // Federated identities (google.com / facebook.com / federated)
        // don't carry an email-shaped issuerAssignedId — picking them up
        // would surface garbage in the grid. The mapper only honours
        // signInType = emailAddress.
        var user = new GraphUser
        {
            Id = "u-4",
            UserPrincipalName = "cpim_xxx@contoso.onmicrosoft.com",
            Mail = null,
            Identities =
            [
                new ObjectIdentity
                {
                    SignInType = "federated",
                    Issuer = "https://accounts.google.com/",
                    IssuerAssignedId = "1234567890",
                },
            ],
        };

        EntraExternalUserMapper.ToSummary(user).Email.Should().Be(
            "cpim_xxx@contoso.onmicrosoft.com",
            "no emailAddress entry → fall through to UPN; the federated sub claim is not a user-facing email");
    }

    [Fact]
    public void ToDetail_MapsRolesArgument_AndLeavesClaimsExternalLoginsEmpty()
    {
        var user = new GraphUser
        {
            Id = "u-5",
            UserPrincipalName = "cpim_yyy@contoso.onmicrosoft.com",
            Identities =
            [
                new ObjectIdentity { SignInType = "emailAddress", IssuerAssignedId = "carol@personal.example" },
            ],
            BusinessPhones = ["+1-555-0100"],
            AccountEnabled = false,
        };

        var detail = EntraExternalUserMapper.ToDetail(user, TwoRoleArray);

        detail.Roles.Should().BeEquivalentTo(TwoRoleArray);
        detail.Claims.Should().BeEmpty("v0.3 doesn't surface Graph extension properties / user attributes yet");
        detail.ExternalLogins.Should().BeEmpty("v0.3 detail page doesn't render the federated identities — slated for v0.4");
        detail.IsEnabled.Should().BeFalse();
        detail.PhoneNumberConfirmed.Should().BeTrue("presence of a businessPhone is the closest Entra equivalent");
        detail.Email.Should().Be("carol@personal.example");
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    public void ToGraphCreate_GeneratesTemporaryPassword_WhenCommandPasswordIsMissing(string? supplied)
    {
        var command = new CreateUserCommand
        {
            Email = "new.user@personal.example",
            UserName = "New User",
            Password = supplied,
        };
        var (graphUser, tempPassword) = EntraExternalUserMapper.ToGraphCreate(
            command,
            tenantDomain: "contoso.onmicrosoft.com",
            () => "GENERATED-PWD-123");

        tempPassword.Should().Be("GENERATED-PWD-123");
        graphUser.PasswordProfile!.Password.Should().Be("GENERATED-PWD-123");
        graphUser.PasswordProfile.ForceChangePasswordNextSignIn.Should().BeTrue(
            "the generated-password path forces a rotation on first sign-in");
    }

    [Fact]
    public void ToGraphCreate_PreservesCallerPassword_AndDoesNotForceChange()
    {
        var (graphUser, tempPassword) = EntraExternalUserMapper.ToGraphCreate(
            new CreateUserCommand { Email = "x@y.com", Password = "ExplicitPassword!1" },
            tenantDomain: "contoso.onmicrosoft.com",
            () => "should-not-be-called");

        tempPassword.Should().Be("ExplicitPassword!1");
        graphUser.PasswordProfile!.ForceChangePasswordNextSignIn.Should().BeFalse(
            "if the admin handed over an explicit password they own the rotation policy");
    }

    [Fact]
    public void ToGraphCreate_NoPhone_StillSetsBusinessPhonesAsEmptyList_NotNull()
    {
        // Same Graph constraint as Workforce: businessPhones rejects an
        // explicit null on the wire — must be the empty list for "no
        // phones". A regression here would land a 400 on every customer
        // create the admin doesn't bother to populate a phone for.
        var (graphUser, _) = EntraExternalUserMapper.ToGraphCreate(
            new CreateUserCommand { Email = "x@y.com", PhoneNumber = null },
            tenantDomain: "contoso.onmicrosoft.com",
            () => "pwd");

        graphUser.BusinessPhones.Should().NotBeNull("Graph rejects null for non-nullable collection types");
        graphUser.BusinessPhones.Should().BeEmpty();
    }

    [Fact]
    public void ToGraphCreate_BuildsIdentitiesEntry_WithEmailAddressSignInType()
    {
        // The whole point of this mapper vs Workforce: the customer-typed
        // email lands in identities[], not in UserPrincipalName. Microsoft
        // server-generates the UPN; we don't set it.
        var command = new CreateUserCommand { Email = "olivia@personal.example", UserName = "Olivia" };
        var (graphUser, _) = EntraExternalUserMapper.ToGraphCreate(
            command,
            tenantDomain: "contoso.onmicrosoft.com",
            () => "pwd");

        graphUser.Identities.Should().NotBeNull().And.HaveCount(1);
        var identity = graphUser.Identities![0];
        identity.SignInType.Should().Be("emailAddress",
            "local-account credential — the password lives in the directory");
        identity.Issuer.Should().Be("contoso.onmicrosoft.com",
            "issuer must match the tenant's initial domain or Graph rejects with 'invalid value'");
        identity.IssuerAssignedId.Should().Be("olivia@personal.example",
            "issuerAssignedId IS the credential the customer signs in with");
        // Workforce sets UserPrincipalName explicitly; External must NOT
        // — Microsoft generates a cpim_ UPN server-side. Setting it would
        // collide with the auto-generation.
        graphUser.UserPrincipalName.Should().BeNull(
            "External UPN is server-generated; setting it ourselves would collide with Microsoft's allocator");
        graphUser.MailNickname.Should().Be("olivia",
            "Graph still requires mailNickname on POST /users regardless of tenant family");
        graphUser.AccountEnabled.Should().BeTrue("newly-created customers default to enabled");
    }

    [Fact]
    public void ToGraphCreate_BlankTenantDomain_Throws()
    {
        var act = () => EntraExternalUserMapper.ToGraphCreate(
            new CreateUserCommand { Email = "x@y.com" },
            tenantDomain: "   ",
            () => "pwd");

        act.Should().Throw<ArgumentException>("the issuer must be a non-blank tenant domain or Graph rejects the create");
    }

    [Fact]
    public void ToGraphUpdate_LeavesUntouchedFieldsNull_SoGraphPatchKeepsThem()
    {
        var patch = EntraExternalUserMapper.ToGraphUpdate(new UpdateUserCommand { UserName = "New display" });
        patch.DisplayName.Should().Be("New display");
        patch.UserPrincipalName.Should().BeNull();
        patch.Mail.Should().BeNull();
        patch.BusinessPhones.Should().BeNull(
            "absent fields in the command must NOT translate to null on the wire — PATCH would clear them");
    }

    [Fact]
    public void ToGraphUpdate_DoesNotPatchIdentities_UpnOrMail_BecauseRewritingCredentialsLocksTheCustomerOut()
    {
        // Identities[] IS the login credential for External customers.
        // The generic admin "save" must not touch it — that'd be a
        // self-lockout footgun. UPN / mail are also untouched (same
        // reasoning as the Workforce mapper).
        var patch = EntraExternalUserMapper.ToGraphUpdate(new UpdateUserCommand
        {
            Email = "new@personal.example",
            UserName = "New display",
            PhoneNumber = "+5511",
        });
        patch.DisplayName.Should().Be("New display");
        patch.BusinessPhones.Should().ContainSingle().Which.Should().Be("+5511");
        patch.Identities.Should().BeNull("rewriting the identities[] would lock the customer out of their own account");
        patch.UserPrincipalName.Should().BeNull();
        patch.Mail.Should().BeNull();
    }

    [Fact]
    public void ToGraphUpdate_BlankPhoneClearsList()
    {
        var patch = EntraExternalUserMapper.ToGraphUpdate(new UpdateUserCommand { PhoneNumber = "   " });
        patch.BusinessPhones.Should().NotBeNull().And.BeEmpty(
            "an explicit empty/whitespace phone is the admin signalling 'remove the number'");
    }

    [Fact]
    public void BuildGraphFilter_Empty_ReturnsNull_SoGraphIsNotPassedEmptyClause()
    {
        EntraExternalUserMapper.BuildGraphFilter(new UserFilter()).Should().BeNull();
    }

    [Theory]
    [InlineData(true, "accountEnabled eq true")]
    [InlineData(false, "accountEnabled eq false")]
    public void BuildGraphFilter_MapsIsEnabledToAccountEnabled(bool enabled, string expected)
    {
        EntraExternalUserMapper.BuildGraphFilter(new UserFilter { IsEnabled = enabled })
            .Should().Be(expected);
    }

    [Fact]
    public void BuildGraphFilter_LockedOutFlipsToAccountEnabledFalse()
    {
        EntraExternalUserMapper.BuildGraphFilter(new UserFilter { IsLockedOut = true })
            .Should().Be("accountEnabled eq false",
                "IsLockedOut = true maps to accountEnabled = false in Entra-land");
    }

    [Fact]
    public void BuildGraphFilter_SearchIncludesIdentitiesIssuerAssignedIdMatch()
    {
        // This is the External-specific bit — searching for the email the
        // customer typed must hit identities/* alongside UPN / mail. The
        // ConsistencyLevel: eventual header (added by the store) is what
        // makes the identities/any predicate legal.
        var filter = EntraExternalUserMapper.BuildGraphFilter(new UserFilter { SearchTerm = "alice" });
        filter.Should().NotBeNull();
        filter.Should().Contain("identities/any",
            "the External adapter has to search inside identities[] so customer-typed emails are findable");
        filter.Should().Contain("issuerAssignedId eq 'alice'");
        filter.Should().Contain("startswith(displayName");
    }

    [Fact]
    public void BuildGraphFilter_SearchEscapesSingleQuotes()
    {
        var filter = EntraExternalUserMapper.BuildGraphFilter(new UserFilter { SearchTerm = "O'Reilly" });
        filter.Should().Contain("O''Reilly",
            "OData filter literals escape single quotes by doubling them — customer search terms come from user input");
    }

    [Fact]
    public void BuildGraphFilter_CombinesMultipleClauses_WithAnd()
    {
        var filter = EntraExternalUserMapper.BuildGraphFilter(new UserFilter
        {
            SearchTerm = "alice",
            IsEnabled = true,
        });

        filter.Should().Contain("accountEnabled eq true").And.Contain("startswith");
        filter.Should().Contain(" and ");
    }
}
